-d C:\Users\Petr\Documents\FPGA\projectSOC\alfaCopy(2)CopyCopy\BitmapFramebuffer\impl\gwsynthesis\Bitmap Framebuffer.vg
-p GW2AR-18C-QFN88P-8
-pn GW2AR-LV18QN88PC8/I7
-cst C:\Users\Petr\Documents\FPGA\projectSOC\alfaCopy(2)CopyCopy\BitmapFramebuffer\src\SoC.cst
-cfg C:\Users\Petr\Documents\FPGA\projectSOC\alfaCopy(2)CopyCopy\BitmapFramebuffer\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
